server:
  port: 8081

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      # 此处配置表示开启自动映射Eureka下发的路由
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: eureka-client-hello-demo
        uri: lb://eureka-client-hello-demo
        predicates:
          - Path=/user/**
        filters:
          - StripPrefix=1
