server:
  port: 28100

spring:
  application:
    name: eureka-client-hello-demo
  security:
    user:
      name: nick
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://nick:123456@peer1.eureka.com:28081/eureka/,http://nick:123456@peer2.eureka.com:28082/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}