server:
  port: 28096

spring:
  application:
    name: platform-service
  profiles:
    active: local
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://nick:123456@peer1.eureka.com:28081/eureka/,http://nick:123456@peer2.eureka.com:28082/eureka/
#