#mysql
spring:

  datasource:
      url: jdbc:mysql://172.16.115.134:3306/my_db?serverTimezone=UTC
#      url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
      username: root
      password: zW123456!
      driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus
mybatis-plus:
#  mapper-locations: com.nick.springcloud.portal.platform.mapper
#  type-aliases-package: com.nick.springcloud.portal.platform.model
  configuration:
    map-underscore-to-camel-case: true